/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.CardLayout;
import javax.swing.JFrame;

/**
 *
 * @author eliomar.campos
 */
public class Home extends javax.swing.JFrame {

    private UsuarioPainel usuarioPainel;
    private CardLayout card;
    
    public Home() {
        initComponents();
        liberarComponentes(false);
        addPaineis();
    }

    private void liberarComponentes(boolean flag){
        painelLateral.setVisible(flag);
        menuArquivo.setEnabled(flag);
        menuCadastros.setEnabled(flag);     
    }
    private void addPaineis(){
        card = (CardLayout) painelPrincipal.getLayout();
        usuarioPainel = new UsuarioPainel();
        painelPrincipal.add(painelLogin, painelLogin.getName());
        painelPrincipal.add(labelLogo, labelLogo.getName());
        painelPrincipal.add(usuarioPainel, usuarioPainel.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        painelLateral = new javax.swing.JPanel();
        botaoHome = new javax.swing.JButton();
        botaoUsuarios = new javax.swing.JButton();
        botaoClientes = new javax.swing.JButton();
        botaoLogout = new javax.swing.JButton();
        painelPrincipal = new javax.swing.JPanel();
        painelLogin = new javax.swing.JPanel();
        painelCentral = new javax.swing.JPanel();
        painelAreaLogin = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        checkLogado = new javax.swing.JCheckBox();
        labelEsqueceuSenha = new javax.swing.JLabel();
        botaoLogin = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        botaoFacebook = new javax.swing.JButton();
        botaoTwitter = new javax.swing.JButton();
        botaoGoogle = new javax.swing.JButton();
        painelUserName = new javax.swing.JPanel();
        txtUser = new javax.swing.JTextField();
        labelUser = new javax.swing.JLabel();
        painelPassword = new javax.swing.JPanel();
        txtPassword = new javax.swing.JPasswordField();
        labelPassword = new javax.swing.JLabel();
        labelImagemBack = new javax.swing.JLabel();
        labelLogo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuArquivo = new javax.swing.JMenu();
        menuConfiguracoes = new javax.swing.JMenuItem();
        menuHelp = new javax.swing.JMenu();
        menuVersao = new javax.swing.JMenuItem();
        menuCadastros = new javax.swing.JMenu();
        menuUsuarios = new javax.swing.JMenuItem();
        menuClientes = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(JFrame.MAXIMIZED_BOTH);

        painelLateral.setBackground(new java.awt.Color(51, 51, 51));

        botaoHome.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        botaoHome.setForeground(new java.awt.Color(255, 255, 255));
        botaoHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/local_32.png"))); // NOI18N
        botaoHome.setText("Home");
        botaoHome.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        botaoHome.setBorderPainted(false);
        botaoHome.setContentAreaFilled(false);
        botaoHome.setFocusPainted(false);
        botaoHome.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botaoHome.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botaoHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoHomeActionPerformed(evt);
            }
        });

        botaoUsuarios.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        botaoUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        botaoUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/user_login_32.png"))); // NOI18N
        botaoUsuarios.setText("Usuários");
        botaoUsuarios.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        botaoUsuarios.setBorderPainted(false);
        botaoUsuarios.setContentAreaFilled(false);
        botaoUsuarios.setFocusPainted(false);
        botaoUsuarios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botaoUsuarios.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botaoUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoUsuariosActionPerformed(evt);
            }
        });

        botaoClientes.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        botaoClientes.setForeground(new java.awt.Color(255, 255, 255));
        botaoClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/clientes_32.png"))); // NOI18N
        botaoClientes.setText("Clientes");
        botaoClientes.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        botaoClientes.setBorderPainted(false);
        botaoClientes.setContentAreaFilled(false);
        botaoClientes.setFocusPainted(false);
        botaoClientes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botaoClientes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        botaoLogout.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        botaoLogout.setForeground(new java.awt.Color(255, 255, 255));
        botaoLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/logout2_32.png"))); // NOI18N
        botaoLogout.setText("Logout");
        botaoLogout.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        botaoLogout.setBorderPainted(false);
        botaoLogout.setContentAreaFilled(false);
        botaoLogout.setFocusPainted(false);
        botaoLogout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botaoLogout.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botaoLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelLateralLayout = new javax.swing.GroupLayout(painelLateral);
        painelLateral.setLayout(painelLateralLayout);
        painelLateralLayout.setHorizontalGroup(
            painelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelLateralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botaoUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botaoHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botaoClientes))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelLateralLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botaoLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        painelLateralLayout.setVerticalGroup(
            painelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelLateralLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(botaoHome)
                .addGap(27, 27, 27)
                .addComponent(botaoUsuarios)
                .addGap(27, 27, 27)
                .addComponent(botaoClientes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botaoLogout)
                .addContainerGap())
        );

        painelPrincipal.setLayout(new java.awt.CardLayout());

        painelLogin.setBackground(new java.awt.Color(0, 153, 255));
        painelLogin.setName("painelLogin"); // NOI18N
        painelLogin.setLayout(new java.awt.GridBagLayout());

        painelCentral.setOpaque(false);
        painelCentral.setLayout(null);

        painelAreaLogin.setOpaque(false);

        jLabel1.setBackground(new java.awt.Color(0, 51, 204));
        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("Login");

        jLabel2.setBackground(new java.awt.Color(0, 51, 204));
        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 153));
        jLabel2.setText("Faça login para continuar");

        checkLogado.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        checkLogado.setForeground(new java.awt.Color(0, 0, 153));
        checkLogado.setText("Manter Logado");
        checkLogado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        labelEsqueceuSenha.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        labelEsqueceuSenha.setForeground(new java.awt.Color(0, 0, 153));
        labelEsqueceuSenha.setText("Esqueceu a senha?");
        labelEsqueceuSenha.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        botaoLogin.setBackground(new java.awt.Color(0, 102, 255));
        botaoLogin.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        botaoLogin.setForeground(new java.awt.Color(255, 255, 255));
        botaoLogin.setText("LOGIN");
        botaoLogin.setBorder(null);
        botaoLogin.setBorderPainted(false);
        botaoLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoLoginActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(0, 51, 204));
        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Ou");

        jLabel5.setBackground(new java.awt.Color(0, 51, 204));
        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Login Com");

        botaoFacebook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/facebook_32.png"))); // NOI18N
        botaoFacebook.setBorderPainted(false);
        botaoFacebook.setContentAreaFilled(false);
        botaoFacebook.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        botaoTwitter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/twitter_32.png"))); // NOI18N
        botaoTwitter.setBorderPainted(false);
        botaoTwitter.setContentAreaFilled(false);
        botaoTwitter.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        botaoGoogle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/google_32.png"))); // NOI18N
        botaoGoogle.setBorderPainted(false);
        botaoGoogle.setContentAreaFilled(false);
        botaoGoogle.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        painelUserName.setBackground(new java.awt.Color(255, 255, 255));
        painelUserName.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        txtUser.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtUser.setForeground(new java.awt.Color(0, 51, 204));
        txtUser.setBorder(null);
        txtUser.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtUser.setMargin(new java.awt.Insets(2, 50, 2, 2));
        txtUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtUserMouseClicked(evt);
            }
        });

        labelUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/user_login_32.png"))); // NOI18N

        javax.swing.GroupLayout painelUserNameLayout = new javax.swing.GroupLayout(painelUserName);
        painelUserName.setLayout(painelUserNameLayout);
        painelUserNameLayout.setHorizontalGroup(
            painelUserNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelUserNameLayout.createSequentialGroup()
                .addComponent(labelUser, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        painelUserNameLayout.setVerticalGroup(
            painelUserNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelUserNameLayout.createSequentialGroup()
                .addGroup(painelUserNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtUser)
                    .addComponent(labelUser, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        painelPassword.setBackground(new java.awt.Color(255, 255, 255));
        painelPassword.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        txtPassword.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(0, 51, 204));
        txtPassword.setBorder(null);
        txtPassword.setMargin(new java.awt.Insets(2, 50, 2, 2));

        labelPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/lock_32.png"))); // NOI18N

        javax.swing.GroupLayout painelPasswordLayout = new javax.swing.GroupLayout(painelPassword);
        painelPassword.setLayout(painelPasswordLayout);
        painelPasswordLayout.setHorizontalGroup(
            painelPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelPasswordLayout.createSequentialGroup()
                .addComponent(labelPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        painelPasswordLayout.setVerticalGroup(
            painelPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPasswordLayout.createSequentialGroup()
                .addGroup(painelPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(labelPassword, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout painelAreaLoginLayout = new javax.swing.GroupLayout(painelAreaLogin);
        painelAreaLogin.setLayout(painelAreaLoginLayout);
        painelAreaLoginLayout.setHorizontalGroup(
            painelAreaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelAreaLoginLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(painelAreaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, painelAreaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(painelAreaLoginLayout.createSequentialGroup()
                            .addGap(109, 109, 109)
                            .addGroup(painelAreaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelAreaLoginLayout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(177, 177, 177))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelAreaLoginLayout.createSequentialGroup()
                                    .addComponent(botaoFacebook, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(9, 9, 9)
                                    .addGroup(painelAreaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(painelAreaLoginLayout.createSequentialGroup()
                                            .addGap(18, 18, 18)
                                            .addComponent(botaoTwitter, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(27, 27, 27)
                                            .addComponent(botaoGoogle, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelAreaLoginLayout.createSequentialGroup()
                                            .addComponent(jLabel5)
                                            .addGap(152, 152, 152))))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelAreaLoginLayout.createSequentialGroup()
                            .addComponent(checkLogado)
                            .addGap(265, 265, 265))
                        .addGroup(painelAreaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(labelEsqueceuSenha)
                            .addComponent(painelPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(painelUserName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botaoLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        painelAreaLoginLayout.setVerticalGroup(
            painelAreaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelAreaLoginLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(63, 63, 63)
                .addComponent(painelUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(painelPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelAreaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkLogado)
                    .addComponent(labelEsqueceuSenha))
                .addGap(21, 21, 21)
                .addComponent(botaoLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(painelAreaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(painelAreaLoginLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botaoGoogle, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelAreaLoginLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(painelAreaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelAreaLoginLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addGap(13, 13, 13)
                                .addComponent(botaoTwitter, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(botaoFacebook, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(37, 37, 37))
        );

        painelCentral.add(painelAreaLogin);
        painelAreaLogin.setBounds(470, 0, 470, 530);

        labelImagemBack.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelImagemBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/welcome.png"))); // NOI18N
        painelCentral.add(labelImagemBack);
        labelImagemBack.setBounds(0, 0, 945, 533);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 945;
        gridBagConstraints.ipady = 533;
        painelLogin.add(painelCentral, gridBagConstraints);

        painelPrincipal.add(painelLogin, "card3");

        labelLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/shopping_512.png"))); // NOI18N
        labelLogo.setName("labelLogo"); // NOI18N
        painelPrincipal.add(labelLogo, "card2");

        menuArquivo.setText("Arquivo");

        menuConfiguracoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/cargos_24.png"))); // NOI18N
        menuConfiguracoes.setText("Configurações");
        menuArquivo.add(menuConfiguracoes);

        menuHelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/warning_32.png"))); // NOI18N
        menuHelp.setText("Help");

        menuVersao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/calendar_16.png"))); // NOI18N
        menuVersao.setText("Versão");
        menuHelp.add(menuVersao);

        menuArquivo.add(menuHelp);

        jMenuBar1.add(menuArquivo);

        menuCadastros.setText("Cadastros");

        menuUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/user_login_32.png"))); // NOI18N
        menuUsuarios.setText("Usuarios");
        menuCadastros.add(menuUsuarios);

        menuClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/clientes_32.png"))); // NOI18N
        menuClientes.setText("Clientes");
        menuCadastros.add(menuClientes);

        jMenuBar1.add(menuCadastros);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painelLateral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 1519, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelLateral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(painelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 771, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoHomeActionPerformed
         card.show(painelPrincipal, labelLogo.getName()); 
    }//GEN-LAST:event_botaoHomeActionPerformed

    private void botaoUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoUsuariosActionPerformed
        card.show(painelPrincipal, usuarioPainel.getName()); 
    }//GEN-LAST:event_botaoUsuariosActionPerformed

    private void txtUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUserMouseClicked
        //jTextField2.setText("");
    }//GEN-LAST:event_txtUserMouseClicked

    private void botaoLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoLoginActionPerformed
       liberarComponentes(true);
       card.show(painelPrincipal, labelLogo.getName()); 
    }//GEN-LAST:event_botaoLoginActionPerformed

    private void botaoLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoLogoutActionPerformed
       liberarComponentes(false);
       card.show(painelPrincipal, painelLogin.getName()); 
    }//GEN-LAST:event_botaoLogoutActionPerformed

   
    public static void main(String args[]) {
           new Home().setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoClientes;
    private javax.swing.JButton botaoFacebook;
    private javax.swing.JButton botaoGoogle;
    private javax.swing.JButton botaoHome;
    private javax.swing.JButton botaoLogin;
    private javax.swing.JButton botaoLogout;
    private javax.swing.JButton botaoTwitter;
    private javax.swing.JButton botaoUsuarios;
    private javax.swing.JCheckBox checkLogado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel labelEsqueceuSenha;
    private javax.swing.JLabel labelImagemBack;
    private javax.swing.JLabel labelLogo;
    private javax.swing.JLabel labelPassword;
    private javax.swing.JLabel labelUser;
    private javax.swing.JMenu menuArquivo;
    private javax.swing.JMenu menuCadastros;
    private javax.swing.JMenuItem menuClientes;
    private javax.swing.JMenuItem menuConfiguracoes;
    private javax.swing.JMenu menuHelp;
    private javax.swing.JMenuItem menuUsuarios;
    private javax.swing.JMenuItem menuVersao;
    private javax.swing.JPanel painelAreaLogin;
    private javax.swing.JPanel painelCentral;
    private javax.swing.JPanel painelLateral;
    private javax.swing.JPanel painelLogin;
    private javax.swing.JPanel painelPassword;
    private javax.swing.JPanel painelPrincipal;
    private javax.swing.JPanel painelUserName;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
